var moStoreAddRequestJSON = {
	"cmd" : "moStoreAdd",
	"storeDetail" : {
		"storeId" : "888800002",
		"storeName" : "storeName",
		"storeStructure" : "F",
		"merchantGroupId" : "184",
		"merchantMember" : "merchantMember",
		"associateStoreId":"204700666",
		"companyName" : "companyName",
		"proprietor" : "proprietor",
		"businessAssociation" : "businessAssociation",
		"abn" : "111",
		"acn" : "222",
		"bdmId" : "333",
		"addrLine1" : "line1",
		"addrLine2" : "line2",
		"addrPostCode" : "444",
		"addrSuburb" : "addrSuburb",
		"addrState" : "addrState",
		"mailAddrSameFlag" : "N",
		"mailAddrLine1" : "mailAddrLine1",
		"mailAddrLine2" : "mailAddrLine2",
		"mailAddrPostCode" : "550011",
		"mailAddrSuburb" : "mailAddrSuburb",
		"mailAddrState" : "mailAddrState",
		"fax" : "10002",
		"phone" : "10003",
		"mobile" : "10004",
		"email" : "11@qq.com",
		"storeSetup" : ["RP" , "WF"],
		"discountRateGroup" : "DR104",
		"commission" : "Y",
		"agreementVer" : "agreementVer",
		"status" : "ACC",
		"statusChangeDate" : "01/01/2013",
		"comments" : "comments",
		"invoiceFaxHo" : "2555",
		"invoiceEmailHo" : "6555",
		"invoiceCcHo" : "202145",
		"invoiceFaxStore" : "8565",
		"invoiceEmailStore" : "4125",
		"invoiceCcStore" : "6523",
		"invoiceAccountName" : "5456",
		"invoiceAccountNumber" : "22221",
		"invoiceAccountBsb" : "12545",
		"trainingChannel" : "1",
		"trainedStaffNum" : 20,
		"callCycle" : "5",
		"implBriefs" : "Y",
		"accreditDocsRDate" : "01/01/2013",
		"accreditDocsCDate" : "01/01/2013",
		"irregular" : "irregular",
		"irregularNotes" : "irregularNotes",
		"productSubmissionRDate" : "02/01/2013",
		"productSubmissionCDate" : "03/01/2013",
		"ccrSubmissionRDate" : "04/01/2013",
		"ccrSubmissionCDate" : "05/01/2013",
		"mbsRDate" : "06/01/2013",
		"mbsCDate" : "07/01/2013",
		"collateralOrderRDate" : "08/01/2013",
		"collateralOrderCDate" : "09/01/2013",
		"executionRDate" : "10/01/2013",
		"executionCDate" : "11/01/2013",
		"statusNotes" : "statusNotes",
		"implRequestDate" : "12/01/2013",
		"firstContractedDate" : "13/01/2013",
		"rolledOutDate" : "14/01/2013",
		"thirdPartyAgreement": "thirdPartyAgreement",
		"accountManager": "accountManager",
		"storeContact1": "storeContact1",
		"storeContact2": "storeContact2",
		"storeContact3": "storeContact3",
		"positionInStore1": "positionInStore1",
		"positionInStore2": "positionInStore2",
		"positionInStore3": "positionInStore3",
		"phoneApplication": "phoneApplication",
		"rapid": "rapid"
	}
};
;
