var wfNewAppRequestJSON = {
	"cmd" : "wfNewApp",
	"isAddon" : true,
	"claimAusResident" : true,
	"claimOver18" : true,
	"claimIncomeOver20k" : true,
	"claimGoodCreditHistory" : true,
	"electronicAccepted" : true,
	"email" : "1234@qq.com",
	"bookletId" : "bookletId",
	"productCode" : "5520",
	"salesPersonId" : "198.25.658.4",
	"promotionTerm" : "aaa",
	"goodsDesc" : "single-sales",
	"financeAmount" : "110.25",
	"isAppForMerchantStaff" : true,
	"staffId" : "43589113",
	"keyFactSheetViewed" : true,
	"declarationPrivacyConsent" : true
};